### ISSUE TITLE
Zambia field work link broken

### ISSUE THREAD

**Issue by kcaylor** [ecohydro/waves_website#28]
The link from the news page to the new Zambia news entry is broken. Maybe the slug name is wrong?

**Comment by Ntkrell** [comment]
Thought I fixed it but apparently not! The page works when I run the site locally so there must be something wrong in the file on GitHub. I will look at this again in a bit.

**Comment by kcaylor** [comment]
My guess is you need a trailing `/` at the end of the permalink? Other posts have one...

**Comment by Ntkrell** [comment]
fixed!

**Comment by kcaylor** [comment]
Great! You can add "closes" (or "fixes" ) #28 in your Commit message. Also, go ahead and submit a pull request to deploy. I setup code review, so I want to see how it works.
