### ISSUE TITLE
Insert space in doi to help formatting

### ISSUE THREAD

**Issue by kcaylor** [ecohydro/waves_website#34]
`Tuholske, C. *et al.* (2017) Thirty years of land use/cover change in the Caribbean&#68 Assessing the relationship between urbanization and mangrove loss in Roatán, Honduras. Applied Geography, doi:10.1016/j.apgeog.2017.08.018`

Should be:
`Tuholske, C. *et al.* (2017) Thirty years of land use/cover change in the Caribbean&#68 Assessing the relationship between urbanization and mangrove loss in Roatán, Honduras. Applied Geography, doi:10.1016/ j.apgeog.2017.08.018`

The space in the doi string allows for better text wrapping on the site.

**Comment by kcaylor** [comment]
Also, there's a `&#68` in the text, title, etc... that should be a `:`, I think.

**Comment by cascadet** [comment]
: is an operator in markdown so I thought I needed to use the code for colon symbol to be translated to HTML correctly

**Comment by kcaylor** [comment]
Finally, can you add this to the YAML metadata:

`header:
    teaser: assets/images/publications/Tuholske2017_1987.png
`

**Comment by kcaylor** [comment]
Yeah. It's weird, but I guess it's not a problem.

**Comment by cascadet** [comment]
Yeah - I will. Do I do a whole new push/pull request?

**Comment by kcaylor** [comment]
Yep. New commit. New pull request. That's why it's best to test these on your local machine first. Otherwise we do a bunch of back-and-forth. But it's good practice to learn how to use github 👍

**Comment by kcaylor** [comment]
Hold on. The title is rendering correctly now. That's super-weird. Anyway, don't change the escape code to the `:`

**Comment by cascadet** [comment]
sounds good - when you can, please remind me how to test the site locally
